export const SWITCH_TOPIC = "SWITCH_TOPIC"

export const GET_WORLD_NEWS_BEGIN   = 'GET_WORLD_NEWS_BEGIN';
export const GET_WORLD_NEWS_SUCCESS = 'GET_WORLD_NEWS_SUCCESS';
export const GET_WORLD_NEWS_ERROR = 'GET_WORLD_NEWS_ERROR';

export const GET_US_NEWS_BEGIN = "GET_US_NEWS_BEGIN"
export const GET_US_NEWS_SUCCESS = 'GET_US_NEWS_SUCCESS';
export const GET_US_NEWS_ERROR = 'GET_US_NEWS_ERROR';

export const GET_SPORTS_NEWS_BEGIN = "GET_SPORTS_NEWS_BEGIN"
export const GET_SPORTS_NEWS_SUCCESS = 'GET_SPORTS_NEWS_SUCCESS';
export const GET_SPORTS_NEWS_ERROR = 'GET_SPORTS_NEWS_ERROR';

export const GET_TECH_NEWS_BEGIN = "GET_TECH_NEWS_BEGIN"
export const GET_TECH_NEWS_SUCCESS = 'GET_TECH_NEWS_SUCCESS';
export const GET_TECH_NEWS_ERROR = 'GET_TECH_NEWS_ERROR';